export const CONSTANTS = {
    SERVER_PATH: 'http://ec2-35-154-36-55.ap-south-1.compute.amazonaws.com:8080/images/img-800x500/',
    BAG_2_BAG_LOGO: 'http://ec2-35-154-36-55.ap-south-1.compute.amazonaws.com:8080/images/logo/app-logo.png',
    TO_CUSTOMER: 'TO_CUSTOMER',
    TO_VENDOR: 'TO_VENDOR',
    TO_CUSTOMER_CARE: 'TO_CUSTOMER_CARE',
    TO_ALL: 'TO_ALL',
    MINISTAY_BOOKING_CONFIRMATION_SMS: 'MINISTAY_BOOKING_CONFIRMATION_SMS',
    REGULARSTAY_BOOKING_CONFIRMATION_SMS: 'REGULARSTAY_BOOKING_CONFIRMATION_SMS',
    NIGHTSTAY_BOOKING_CONFIRMATION_SMS: 'NIGHTSTAY_BOOKING_CONFIRMATION_SMS',
    PAYMENT_CONFIRMATION_SMS: 'PAYMENT_CONFIRMATION_SMS',
    BOOKING_CANCELLATION_SMS: 'BOOKING_CANCELLATION_SMS',
}